server:
  port: 8000

boundaries:
  top: 900
  left: 1500

logging:
  excluded:
    - css
    - js
    - ico

cells:
  cell mass: 2
  # cell spawn rate, 1-10
  spawn rate: 3
  # all available colors: https://www.w3schools.com/colors/colors_names.asp
  colors:
    - red
    - blue
    - orange
    - green
    - rebeccapurple
    - maroon